# action.yml
name: 'RIPS Security Scan'
author: 'RIPS Technologies GmbH'
description: 'Performs a security scan (static code analysis) via your RIPS installation (On-Premises or SaaS).'
inputs:
  application-id:
    description: 'Id of the application the scan belongs to'
    required: true
  additional-parameters:
    description: 'Additional parameters. (https://kb.ripstech.com/doc/latest/tooling/rips-cli)'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.application-id }}
    - ${{ inputs.additional-parameters }}
branding:
  icon: shield
  color: yellow